---
harden_linux_deploy_user: berkeleytrue
harden_linux_deploy_user_public_keys:
  - /home/berkeleytrue/.ssh/id_ed25519.pub

harden_linux_sshd_settings:
  '^Port ': Port {{ default_ssh_port }}    # Set SSHd port

harden_linux_deploy_user_shell: /bin/zsh
harden_linux_ufw_rules:
  - rule: allow
    to_port: '{{ default_ssh_port }}'
    protocol: tcp

harden_linux_optional_packages:
  - neovim
  - dnsutils
  - curl
  - zsh

fuse_mount_points:
  # yamllint disable rule:line-length
  - name: /mnt/pari1
    src: /dev/disk/by-id/ata-WDC_WD40EFAX-68JH4N0_WD-WX62D10LE1SE
    fs: ext4
    content: true

  - name: /mnt/disk1
    src: /dev/disk/by-id/ata-WDC_WD40EFAX-68JH4N0_WD-WX62D10LEJHE
    fs: ext4
    fuse: true
    content: true

  - name: /mnt/disk2
    src: /dev/disk/by-id/ata-WDC_WD40EFAX-68JH4N0_WD-WX62D10LEKV3
    fs: ext4
    fuse: true

  - name: /mnt/disk3
    src: /dev/disk/by-id/ata-WDC_WD40EFAX-68JH4N0_WD-WX62D10LEN1A
    fs: ext4
    fuse: true
  # yamllint enable rule:line-length

fuse_main_mount_point: /mnt/storage
