---
- name: Install sudo
  package:
    pkg: sudo
    state: present

- name: Add authorized keys for deploy user
  authorized_key:
    user: '{{ harden_linux_deploy_user }}'
    key: "{{ lookup('file', item) }}"
  loop: '{{ harden_linux_deploy_user_public_keys }}'
  when: harden_linux_deploy_user_public_keys is defined
  tags:
    - user

- name: Ensure deploy user present in /etc/sudoers.d/{{ harden_linux_deploy_user
    }}
  template:
    src: etc/sudoers.d/deployuser.j2
    dest: /etc/sudoers.d/{{ harden_linux_deploy_user }}
    owner: root
    group: root
    mode: '0400'
  tags:
    - user
    - sudo

- name: Ensure deploy user is absent in /etc/sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: ^{{ harden_linux_deploy_user }} ALL
    state: absent
  tags:
    - user
    - sudo
