---
- name: Install sshguard package
  package:
    name: sshguard
    state: present
  tags:
    - sshguard

- name: Register sshd port setting in ssd_config
  shell: grep -E '^Port ' /etc/ssh/sshd_config || echo 'Port 22'
  register: harden_linux__ssh_port_tmp
  changed_when: false
  failed_when: false
  tags:
    - sshguard

- name: Register sshd port fact
  set_fact:
    harden_linux__ssh_port: '{{ harden_linux__ssh_port_tmp.stdout.split()[1] | trim
      }}'
  tags:
    - sshguard

- name: Update UFW before.rules
  blockinfile:
    path: /etc/ufw/before.rules
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
    insertafter: ^-A ufw-before-output -o lo -j ACCEPT
    block: |
      # hand off control for sshd to sshguard
      :sshguard - [0:0]
      -A ufw-before-input -p tcp --dport {{ harden_linux__ssh_port }} -j sshguard
  notify:
    - reload ufw

- name: Update sshguard whitelist file
  lineinfile:
    dest: '{{ harden_linux_sshguard_whitelist_file }}'
    regexp: ^{{ whitelist_entry }}
    line: '{{ whitelist_entry }}'
    state: present
  loop: '{{ harden_linux_sshguard_whitelist }}'
  loop_control:
    loop_var: whitelist_entry
  notify:
    - restart sshguard
  tags:
    - sshguard
