---
all:
  children:
    marceline:
      hosts:
        pve.lan:

    omv:
      hosts:
        omv.lan:

    rancher:
      hosts:
        rancher.lan:
          ansible_user: rancher

    vms:
      children:
        omv:
