---
- name: Get Raspberry host
  hosts: localhost
  gather_facts: true
  vars_prompt:
  - name: target_host
    prompt: Please enter the target host IP
    private: false

  - name: cur_port
    prompt: Please enter the current ssh port
    private: false

  - name: cur_user
    prompt: Please enter current user
    default: ubuntu
    private: false

  - name: cur_pass
    prompt: Please enter current user pass
    default: ubuntu
    private: true

  tasks:
    - add_host:
        name: '{{ target_host }}'
        groups: dynamically_created_hosts
        ansible_ssh_user: '{{ cur_user }}'
        ansible_ssh_password: '{{ cur_pass }}'
        ansible_ssh_port: '{{ cur_port }}'

- name: Init ubuntu
  hosts: dynamically_created_hosts
  become: true
  become_user: root

  vars_files:
    - vars/main.yml
    - vars/secrets.yml

  vars_prompt:
  - name: new_hostname
    prompt: Please enter new hostname
    private: false

  handlers:
    - name: reboot
      command: reboot now

  pre_tasks:
    - name: Install sudo
      package:
        pkg: sudo
        state: present

    - name: Add deploy user
      user:
        name: '{{ harden_linux_deploy_user }}'

    - name: Add authorized keys for deploy user
      authorized_key:
        user: '{{ harden_linux_deploy_user }}'
        key: "{{ lookup('file', item) }}"
      loop: '{{ harden_linux_deploy_user_public_keys }}'

    - name: Ensure deploy user present in /etc/sudoers.d/{{ harden_linux_deploy_user }}
      template:
        src: etc/sudoers.d/deployuser.j2
        dest: /etc/sudoers.d/{{ harden_linux_deploy_user }}
        owner: root
        group: root
        mode: '0400'

    - name: Change hostname
      hostname:
        name: '{{ new_hostname }}'
      notify: reboot

    - name: Enable cgroup if not already enabled
      lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: true
        regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
        line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
      notify: reboot

  roles:
    - harden-linux
