---
# accessLog:
#   filePath: /var/log/access.log
#   format: json
#
#   fields:
#     defaultMode: drop
#     names:
#       RouterName: keep
#       ServiceName: keep
#       RequestAddr: keep
#       RequestHost: keep
#       RequestMethod: keep
#       RequestPath: keep
#       RequestProtocol: keep
#       RequestScheme: keep
#       ClientHost: keep

log:
  level: INFO
  filePath: /var/log/traefik.log

api:
  dashboard: true
  debug: true
  insecure: true

entrypoints:
  web:
    address: :80
  secureweb:
    address: :443
    http:
      tls:
        certResolver: cloudflare

  # for pihole
  # dns:
  #   address: :53
  # dnsudp:
  #   address: :53/udp
  # dnsovertls:
  #   address: :853

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false

  file:
    filename: /config.yml

certificatesResolvers:
  cloudflare:
    acme:
      email: '{{ cloudflare_email }}'
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53
