---
- name: Stat storage is mounted
  stat:
    path: '{{ fuse_main_mount_point }}'
  register: fuse_mount_stat

- name: Fail when no storage
  fail:
    msg: Storage not mounted
  when: fuse_mount_stat.stat.isdir is false

- name: Create SMB group
  group:
    name: smbgroup
    system: true

- name: Create SMB user
  user:
    name: smbuser
    system: true
    create_home: false
    group: smbgroup
    # no login allowed
    shell: /bin/false

- name: Create share dirs
  file:
    name: '{{ fuse_main_mount_point }}/share/{{ item }}'
    state: directory
    owner: smbuser
    group: smbgroup
  loop:
    - public

- name: Install
  apt:
    name: samba
    state: present

- name: Make config dir
  file:
    name: /etc/samba
    owner: root
    group: root
    state: directory

- name: Copy config
  copy:
    src: etc/samba/smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
  notify:
    - restart samba service

- name: Ensure samba service
  service:
    name: smbd
    state: started

# requires sma
- name: Allow samba UFW
  ufw:
    rule: allow
    name: Samba
