---
- name: start docker service
  systemd:
    name: docker
    state: started

- name: systemd daemon-reload
  systemd:
    daemon_reload: true

- name: restart docker service
  service:
    name: docker
    state: restarted
