---
version: '2'

volumes:
  data:

networks:
  web:
    external: true

services:
  storedown:
    container_name: storedown
    image: ghcr.io/berkeleytrue/storedown:latest
    restart: unless-stopped
    networks:
      - web
    depends_on:
      - storedown_couchdb
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https

      # service
      - traefik.http.services.storedown-service.loadbalancer.server.port=80

      # web
      - traefik.http.routers.storedown-web.entrypoints=web
      - traefik.http.routers.storedown-web.rule=Host(`storedown.{{ TRAEFIK_PUBLIC_URL }}`)
      - traefik.http.routers.storedown-web.service=storedown-service
      - traefik.http.routers.storedown-web.middlewares=https-redirect,sslheader

      # secure
      - traefik.http.routers.storedown-secure.rule=Host(`storedown.{{ TRAEFIK_PUBLIC_URL }}`)
      - traefik.http.routers.storedown-secure.entrypoints=secureweb
      - traefik.http.routers.storedown-secure.service=storedown-service

  storedown_couchdb:
    container_name: storedown_couchdb
    image: couchdb
    restart: unless-stopped
    volumes:
      - data:/opt/couchdb/data
    networks:
      - web
    environment:
      COUCHDB_USER: storedown
      COUCHDB_PASSWORD: '{{ storedown_couchdb_password }}'

    labels:
      - traefik.enable=true
      - traefik.http.middlewares.storedown-couchdb-stripprefix.stripprefix.prefixes=/_db

      # service
      - traefik.http.services.storedown-couchdb.loadbalancer.server.port=5984

      # secure
      - traefik.http.routers.storedown-couchdb.rule=Host(`storedown.{{ TRAEFIK_PUBLIC_URL }}`) && PathPrefix(`/_db`)
      - traefik.http.routers.storedown-couchdb.entrypoints=secureweb
      - traefik.http.routers.storedown-couchdb.service=storedown-couchdb
      - traefik.http.routers.storedown-couchdb.middlewares=storedown-couchdb-stripprefix

      # storeleft access
      - traefik.http.routers.storeleft-couchdb.rule=Host(`couchdb.{{ TRAEFIK_PUBLIC_URL }}`)
      - traefik.http.routers.storeleft-couchdb.entrypoints=secureweb
      - traefik.http.routers.storeleft-couchdb.service=storedown-couchdb
      - traefik.http.routers.storeleft-couchdb.middlewares=storedown-couchdb-stripprefix
