---
- name: omv.extras.check if extras installed
  command: dpkg --get-selections | grep openmediavault-omvextrasorg | wc -l
  register: extras_installed

- name: omv.extras.download-extras-script
  get_url:
    url: https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install
    dest: /tmp/omv-install-extras.sh
    mode: 0755
  when: extras_installed != 1

- name: omv.extras.install-extras
  command: bash /tmp/omv-install-extras.sh
  when: extras_installed != 1

- name: omv.extras.install omv-snapraid
  apt:
    state: present
    name:
      - openmediavault-snapraid
  when: extras_installed != 1
