---
- name: Create Parity disks
  set_fact:
    snapraid_parity_disks: "{{ fuse_mount_points | rejectattr('fuse', 'defined')\
      \ }}"
    snapraid_data_disks: "{{ fuse_mount_points | selectattr('fuse', 'defined') |\
      \ selectattr('fuse', 'equalto', true) }}"

- name: Debug parity derivations
  debug:
    var: snapraid_parity_disks

- name: Debug data derivations
  debug:
    var: snapraid_data_disks

- name: Check valid configuration
  block:
    - name: Ensure data disks defined
      fail:
        msg: No data disks defined
      when: snapraid_data_disks | length == 0

    - name: Ensure parity disks defined
      fail:
        msg: No parity disks defined
      when: snapraid_parity_disks | length == 0

    - name: Ensure content disks defined
      fail:
        msg: No content files defined
      when:
        - snapraid_content_files | length == 0
        - snapraid_data_disks | selectattr('content', 'defined') | selectattr('content',
          'equalto', true) | length == 0
        - snapraid_parity_disks | selectattr('content', , 'defined') | selectattr('content',
          'equalto', true) | length == 0

- name: install snapraid config file
  template:
    src: snapraid.conf.j2
    dest: /etc/snapraid.conf
    owner: root
    group: root
    mode: 0775
