---
- name: build.create directory
  file:
    dest: "{{ build_path }}"
    state: directory
  when: pkg_check.rc == 1

- name: build.copy script
  template:
    src: build.jinja
    dest: "{{ build_path }}/build.sh"
    mode: 0775
  when: pkg_check.rc == 1

- name: build.copy Dockerfile
  copy:
    src: Dockerfile
    dest: "{{ build_path }}"
    mode: 0775
  when: pkg_check.rc == 1

- name: build.SnapRAID .deb
  command: "{{ build_path }}/build.sh"
  become: true
  when: pkg_check.rc == 1

- name: build.Install .deb file
  apt:
    deb: "{{ build_path }}/build/snapraid-from-source.deb"
  become: true
  when: pkg_check.rc == 1
