---
- name: create directory
  file:
    dest: '{{ snapraid_build_path }}'
    state: directory
    mode: 0700

- name: copy script
  template:
    src: build.jinja
    dest: '{{ snapraid_build_path }}/build.sh'
    mode: 0775

- name: copy Dockerfile
  copy:
    src: Dockerfile
    dest: '{{ snapraid_build_path }}'
    mode: 0775

- name: build .deb
  command: '{{ snapraid_build_path }}/build.sh'
  become: true
  changed_when: true

- name: Install .deb file
  apt:
    deb: '{{ snapraid_build_path }}/build/snapraid-from-source.deb'
  become: true
