---
# SnapRAID from source, built in a Docker container
- name: check if snapraid is installed
  command: dpkg-query -W snapraid
  ignore_errors: true
  register: is_installed
  changed_when: is_installed.rc != 0

- name: install snapraid?
  set_fact:
    install_snapraid: "{{ snapraid_force_install == true or is_installed.failed == true }}"

- name: build snapraid from source in a container
  import_tasks: build-snapraid.yml
  when: install_snapraid
