---
# tasks file for roles/docker-on-prox
- name: install packages required by docker
  apt:
    # allow apt to use https
    # needed for docker
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: true

- name: add docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    url: "{{ apt_key_url }}"
    state: present
  register: add_repository_key
  ignore_errors: true

- name: add docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: true
    mode: "0644"
    state: present

- name: install (or update) docker package
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: "{{ 'latest' if update_docker_package else 'present' }}"
    update_cache: true
  notify:
    - systemd daemon-reload
    - restart docker service

- name: start docker
  service:
    name: docker
    state: started
