---
- name: Ensure Dir
  file:
    path: '{{ ansible_env.HOME }}/portainer'
    mode: 0755
    state: directory


- name: Ensure compose file
  template:
    src: portainer/docker-compose.yml
    dest: '{{ ansible_env.HOME }}/portainer/docker-compose.yml'
    mode: 0644

- name: Ensure docker network
  docker_network:
    name: web

- name: Ensure Container is up
  docker_compose:
    project_name: portainer
    project_src: '{{ ansible_env.HOME }}/portainer'
