---
version: '2'

services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher_container
    restart: unless-stopped
    privileged: true
    networks:
      - web
    environment:
      - AUDIT_LEVEL=1
    volumes:
      - /opt/rancher:/var/lib/rancher
      - /var/log/rancher/auditlog:/var/log/auditlog
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.middlewares.rancher-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https

      - traefik.http.routers.rancher-web.entrypoints=web
      - traefik.http.routers.rancher-web.rule=Host(`rancher.{{ TRAEFIK_PUBLIC_URL }}`)
      - traefik.http.routers.rancher-web.middlewares=traefik-https-redirect,sslheader

      - traefik.http.routers.rancher-secure.entrypoints=secureweb
      - traefik.http.routers.rancher-secure.rule=Host(`rancher.{{ TRAEFIK_PUBLIC_URL }}`)
      - traefik.http.routers.rancher-secure.service=rancher-service

      - traefik.http.services.rancher-service.loadbalancer.server.port=80

networks:
  web:
    external: true
