---
- name: Ensure Dir {{ item.name }}
  ansible.builtin.file:
    path: '{{ container_home }}/{{ item.name }}'
    mode: "0755"
    state: directory

- name: Ensure Compose file {{ item.name }}
  ansible.builtin.template:
    src: '{{ item.name }}/docker-compose.yml'
    dest: '{{ container_home }}/{{ item.name }}/docker-compose.yml'
    mode: "0644"

- name: Ensure Config file {{ item.name }}
  ansible.builtin.template:
    src: '{{ item.name }}/{{ item.config }}'
    dest: '{{ container_home }}/{{ item.name }}/{{ item.config }}'
    mode: "0644"
  when: item.config is defined

- name: Ensure Container is up {{ item.name }}
  community.docker.docker_compose:
    project_name: '{{ item.name }}'
    project_src: '{{ container_home }}/{{ item.name }}'
