---
version: '3.1'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    networks:
      - web
    volumes:
      - kuma-db:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https

      # service
      - traefik.http.services.kuma-service.loadbalancer.server.port=3001

      # web
      - traefik.http.routers.kuma-web.entrypoints=web
      - traefik.http.routers.kuma-web.rule=Host(`kuma.{{ TRAEFIK_PUBLIC_URL }}`)
      - traefik.http.routers.kuma-web.service=kuma-service
      - traefik.http.routers.kuma-web.middlewares=https-redirect,sslheader

      # secure
      - traefik.http.routers.kuma-secure.rule=Host(`kuma.{{ TRAEFIK_PUBLIC_URL }}`)
      - traefik.http.routers.kuma-secure.entrypoints=secureweb
      - traefik.http.routers.kuma-secure.service=kuma-service


volumes:
  kuma-db:

networks:
  web:
    external: true
