---
- name: base.ensure os is up to date
  apt:
    update_cache: true
    upgrade: full
    cache_valid_time: 300

- name: base.install packages
  apt:
    state: present
    name:
      # A library that makes it possible to implement a filesystem in  userspace
      - mergerfs
      # CLI curses-based monitoring tool
      - glances
      - git
      - htop
      # Display bandwidth usage on an interface
      - iftop
      # View I/O usage of processes
      - iotop
      # Utility for network discovery and security auditing
      - nmap
      - openssh-server
      # Control and monitor S.M.A.R.T. enabled ATA and SCSI Hard Drives
      - smartmontools
      - tmux
      - wget
  tags:
    - packages

- name: base.create /mnt points
  file:
    dest: "{{ item.name }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  loop: "{{ mntpnts }}"

- name: base.create storage mnt
  file:
    dest: "{{ fusepnt }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777

- name: base.ensure fs on disks
  filesystem:
    fstype: "{{ item.fs }}"
    dev: "{{ item.src }}"
  loop: "{{ mntpnts }}"

- name: base.mount disks
  mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    # change to 'mounted' to auto mount
    state: present
  loop: "{{ mntpnts }}"

- name: base.mount mergerfs array
  mount:
    name: "{{ fusepnt }}"
    src: /mnt/disk*
    opts: direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs
    fstype: fuse.mergerfs
    # change to 'mounted' to auto mount
    state: present
