---
- name: base.ensure os is up to date
  apt:
    update_cache: true
    upgrade: full
    cache_valid_time: 300

- name: base.install packages
  apt:
    state: present
    name:
      # A library that makes it possible to implement a filesystem in  userspace
      - mergerfs
      - fuse
      # CLI curses-based monitoring tool
      - glances
      - git
      - htop
      # Display bandwidth usage on an interface
      - iftop
      # View I/O usage of processes
      - iotop
      # Utility for network discovery and security auditing
      - nmap
      - openssh-server
      # Control and monitor S.M.A.R.T. enabled ATA and SCSI Hard Drives
      - smartmontools
      - tmux
      - wget
  tags:
    - packages
