---
version: '3'

services:
  application:
    container_name: nextcloud
    image: nextcloud:{{ nextcloud_version }}-apache
    restart: unless-stopped
    logging:
      driver: journald
    depends_on:
      - database
      - redis
    volumes:
      - nextcloud-db:/var/www/html
    environment:
      POSTGRES_DATABASE: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: '{{ nextcloud_database_password }}'
      POSTGRES_HOST: nextcloud-postgres:3306

      REDIS_HOST: nextcloud-redis
      TRUSTED_PROXIES: 172.18.0.0/16
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav
      - traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/

      # service
      - traefik.http.services.nextcloud-service.loadbalancer.server.port=80

      # web
      - traefik.http.routers.nextcloud-web.entrypoints=web
      - traefik.http.routers.nextcloud-web.rule=Host(`nextcloud.{{ TRAEFIK_PUBLIC_URL }}`)
      - traefik.http.routers.nextcloud-web.service=nextcloud-service
      - traefik.http.routers.nextcloud-web.middlewares=https-redirect,sslheader

      # secure
      - traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.{{ TRAEFIK_PUBLIC_URL }}`)
      - traefik.http.routers.nextcloud-secure.entrypoints=secureweb
      - traefik.http.routers.nextcloud-secure.service=nextcloud-service
      - traefik.http.routers.nextcloud-secure.middlewares=nextcloud-dav

  database:
    container_name: nextcloud-postgres
    image: postgres:14-alpine
    logging:
      driver: journald
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: '{{ nextcloud_database_password }}'
    volumes:
      - nextcloud-postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - web

  redis:
    container_name: nextcloud-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - nextcloud-redis:/data
    networks:
      - web
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  nextcloud-db:
  nextcloud-postgres:
  nextcloud-redis:

networks:
  web:
    external: true
