---
- name: Uninstall old versions of Docker
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent

- name: Install packages required by docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - python3-pip
    state: present
    update_cache: true

- name: Install pips required by ansible docker collection
  pip:
    name:
      - docker
      - docker-compose
    state: present

- name: Add docker repository key
  apt_key:
    id: '{{ apt_key_sig }}'
    url: '{{ apt_key_url }}'
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Add docker repository and update apt cache
  apt_repository:
    repo: '{{ apt_repository }}'
    mode: '0644'
    update_cache: true
    state: present

- name: Install (or update) docker package
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: "{{ 'latest' if update_docker_package else 'present' }}"
    update_cache: '{{ update_docker_package }}'
  notify:
    - systemd daemon-reload
    - restart docker service

- name: start docker
  systemd:
    name: docker
    state: started
